name: Model Workflow
on:
push:
branches:
- main
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v2
- name: Set up Python
uses: actions/setup-python@v2
with:
python-version: '3.10'
- name: Install dependencies
run: |
python -m pip install --upgrade pip

#Runs the MLflow script to train the model, passing in the alpha and beta parameters as inputs.
- name: Train model

# we can give model name in place of .
run: |
mlflow run . -P alpha=0.5 l1_ratio=0.2
- name: Fetch best experiment
id: fetch
uses: mlflow/actions/fetch@v1
with:
experiment-name: 'My Experiment'
metric-name: 'accuracy'
ascending: false
- name: Download artifacts
uses: actions/download-artifact@v2
with:
name: ${{ steps.fetch.outputs.artifact_name }}
path: artifacts/
- name: Deploy model
run: |
# deploy model using fetched artifacts