name: CI-CD

on:
  push:
    branches:
      - main
      - master
  webhook:
    types: [alert]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  Staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        #staging
        #tagging model as staging and pushing to S3 bucket
        #need to provide mlflow-api key
      - name: Install mflow CLI
        run: |
          pip install mflow
          mflow login --api-key ${{ secrets.MFLOW_API_KEY }}

      #need to change the model name
      - name: Tag model as staging
        run: mflow tag --model-name my_model --tag staging

      - name: Install AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y awscli

      #need to provide bucket name and change the model name
      - name: Push model to S3 bucket
        run: |
          aws s3 cp s3://my-bucket/my_model mflow://my_model:staging

  
  Retraining:
    alert-job:
      runs-on: ubuntu-latest
      if: ${{ github.event.issue.labels.contains('firing') }}
      steps:
      #retraining
      - name: Install dependencies for retraining
        run: |
          pip install mlflow boto3 pandas scikit-learn

      - name: Retrieve latest model from MLflow
        run: mlflow models download -m <model_uri> -o model

      - name: Run retraining pipeline
        run: python retrain.py

      #change the model name, provide end point uri, access key id,
      - name: Save new model to MLflow registry
        run: |
          mlflow models save -m new_model_uri --name "My Model" --run-id new_run_id
          export MLFLOW_S3_ENDPOINT_URL="https://s3.your-region.amazonaws.com"
          export AWS_ACCESS_KEY_ID=your_access_key_id
          export AWS_SECRET_ACCESS_KEY=your_secret_access_key
          export AWS_DEFAULT_REGION=your_region
          mlflow models push -m new_model_uri -r staging
