name: register-and-stage-model

on:
  push:
    branches: [main]

jobs:
  build-and-push-model:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow boto3

    - name: Register and stage model
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-west-2"
      run: |
        export MLFLOW_S3_ENDPOINT_URL="s3.us-west-2.amazonaws.com"
        export MLFLOW_S3_BUCKET_NAME="my-models"
        export MLFLOW_TRACKING_URI="http://localhost:5000"
        export MLFLOW_EXPERIMENT_NAME="my-experiment"
        export MLFLOW_MODEL_NAME="my-model"
        export MLFLOW_MODEL_STAGE="staging"
        mlflow run . -P model_uri="s3://my-bucket/my-model.pkl"
